---

- hosts: foreman
  tasks:
    - name: Install Puppet
      yum:
        name: 'https://yum.puppet.com/puppet6-release-el-8.noarch.rpm'
        state: present
        validate_certs: no
        disable_gpg_check: yes

    - name: Reset ruby module
      shell:
        cmd: dnf module reset ruby

    - name: Enable ruby module
      shell:
        cmd: dnf -y module enable ruby:2.7

    - name: Enable Forman Repo
      yum:
        name: 'https://yum.theforeman.org/releases/2.5/el8/x86_64/foreman-release.rpm'
        state: present
        validate_certs: no
        disable_gpg_check: yes

    - name: Download Foreman installer
      yum:
        name: foreman-installer
        state: present
        validate_certs: no
        disable_gpg_check: yes

    - name: Run foreman installer
      shell:
        cmd: foreman-installer
        
    - name: permit traffic in default zone for tcp
      firewalld:
        port: "{{ item }}"/tcp
        permanent: yes
        immediate: yes
        state: enabled
      with_items:
       - 22
       - 53
       - 80
       - 443
       - 3000
       - 8140
       - 3306
       - 5432
       - 8443
       - 5910-5930
    
    - name: permit traffic in default zone for udp
      firewalld:
        port: 67-69/udp
        permanent: yes
        immediate: yes
        state: enabled  
    
    - name: Reload firewalld 
      systemd:
        name: firewalld
        state: reloaded
