---

- hosts: foreman
  tasks:
    - name: Install Puppet
      yum:
        name: 'https://yum.puppet.com/puppet6-release-el-8.noarch.rpm'
        state: present
        validate_certs: no
        disable_gpg_check: yes

    - name: Reset ruby module
      shell:
        cmd: dnf module reset ruby

    - name: Enable ruby module
      shell:
        cmd: dnf -y module enable ruby:2.7

    - name: Enable Forman Repo
      yum:
        name: 'https://yum.theforeman.org/releases/2.5/el8/x86_64/foreman-release.rpm'
        state: present
        validate_certs: no
        disable_gpg_check: yes

    - name: Download Foreman installer
      yum:
        name: foreman-installer
        state: present
        validate_certs: no
        disable_gpg_check: yes

    - name: Run foreman installer
      shell:
        cmd: foreman-installer
